= Jiang Lingshuo - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Bamboo
Bamboo is a desktop address book application developed as part of a Software Engineering module requirement.
The target audience is students or possibly business people as Bamboo provides an easy but efficient approach to
manage contacts. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java,
and has about 22 kLoC.

*Code contributed*:[https://github.com/CS2103AUG2017-W09-B4/main/blob/master/collated/main/jianglingshuo.md[Functional code]][https://github.com/CS2103AUG2017-W09-B4/main/blob/master/collated/test/jianglingshuo.md[Test code]]

=== Enhancement Added: Group Function & Find Function

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=find]

include::../UserGuide.adoc[tag=add]

#End of Extract#

---

==== Justification

* Enhancing find functions is essential for a large size address book. By allowing multiple ways of finding,
users could actually access the contacts by remembering anything, names, emails, address... and even
partial name searching is supported

* Enhancing add functions has great practical value for users. Normally users do not have every detail of their contacts.
Normally, people may want to save their contact with limited knowledge of their phones, emails and addresses.
Especially for students and business people, adding a person with missing field is convenient and require less for users.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=find]

include::../DeveloperGuide.adoc[tag=add]

#End of Extract#

---
=== Enhancement Proposed: Generate QR code for adding person

Support generating QR code for existing contacts. Scanning the QR code will generate add command
instructions for another user. This enhancement would increase the interactive functionality between users.

=== Other contributions

* Write Test Case Group Test (Pull requests https://github.com/CS2103AUG2017-W09-B4/main/pull/84[#84])
* Write System Tests for add and find command (Pull requests https://github.com/CS2103AUG2017-W09-B4/main/pull/100[#100])

== Project:

{Optionally (not graded), you may include other projects in your portfolio.}
